add runInTransaction and wrapInTransaction
odavid/typeorm-transactional-cls-hooked pull request #94
Opened 2021-03-30 16:55 UTC by lytc

2021-04-03 16:18 UTC, odavid requested changes

2021-04-03 16:18 UTC, odavid commented on package.json
> +    "delay": "^5.0.0"
Please change this dependency to be a dev dependency

2021-04-03 16:18 UTC, odavid commented on src/wrapInTransaction.ts
> +}
Please [add a newline](https://unix.stackexchange.com/questions/18743/whats-the-point-in-adding-a-new-line-to-the-end-of-a-file) here...

2021-04-03 16:22 UTC, odavid commented
Hi @lytc, thanks for the contribution!

I feel you also need to add the `runInTransaction` function to the exports within the index.ts

2021-04-06 14:18 UTC, koenpunt commented
Not sure if this is the correct thread to bring this up, but I feel it might be related; I'm using this library indirectly (through [typeorm-test-transactions](https://www.npmjs.com/package/typeorm-test-transactions)), and I was wondering if it would possible to have separate "start" and "stop" transaction methods? So not a function wrapper (or decorator).

I hope to be able to use it in before/after hooks of jest, to automatically "wrap" every test in a transaction;

```ts
beforeEach(() => {
  startTransaction();
});

test('do something with the database', async () => {
    await someDbAction();
});

afterEach(() => {
  rollbackTransaction();
});
```

2021-04-07 15:34 UTC, lytc commented
> Hi @lytc, thanks for the contribution!
> 
> I feel you also need to add the `runInTransaction` function to the exports within the index.ts

2021-04-07 15:36 UTC, lytc commented
Hi @odavid ,
Thanks for your review, I make the change regarding to your comments!

2021-05-15 09:26 UTC, merged

2021-05-15 09:38 UTC, odavid commented
Thank you!